Oasis/Controllers/Credito/PresupuestoController.cs
using Oasis.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Oasis.ViewModel;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Data.Entity;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Oasis.Models.Login;

namespace Oasis.Controllers.Credito
{
    [CustomAuthorize(Roles = "Bodega")]
    public class PresupuestoController : Controller
    {
        public class EditarDetallePresupuesto
        {
            public DetallePresupuesto presupuesto { get; set; }
            public int id_presupuesto { get; set; }
        }



        [HttpGet]
        public ActionResult DuplicarPresupuesto(int id_presupuesto)
        {
            as2oasis oasis = new as2oasis();
            AS2Context as2 = new AS2Context();
            var presupuesto =
                oasis
                .presupuesto_cabecera
                .AsEnumerable()
                .Where(x => x.id_presupuesto == id_presupuesto)
                .Select(x => new presupuesto_cabecera
                {
                    id_presupuesto = x.id_presupuesto,
                    descripcion = x.descripcion,
                    empresa = x.empresa,
                    sucursal = x.sucursal,
                    fecha_desde = x.fecha_desde,
                    fecha_hasta = x.fecha_hasta
                })
                .First();

            List<Presupuesto_Vendedor_Detalle> detallePresupuesto =
                oasis.Presupuesto_Vendedor_Detalle
                .AsEnumerable()
                .Where(x => x.id_presupuesto == id_presupuesto)
                .ToList();

            ViewBag.DetallePresupuesto = detallePresupuesto;

            var detalleP = new DetallePresupuesto();
            detalleP.id_presupuesto = presupuesto.id_presupuesto;
            detalleP.empresa = presupuesto.empresa;
            detalleP.sucursal = presupuesto.sucursal;
            detalleP.descripcion = presupuesto.descripcion;
            detalleP.fecha_desde = presupuesto.fecha_desde;
            detalleP.fecha_hasta = presupuesto.fecha_hasta;
            detalleP.ListaPresupuestoDetalle = detallePresupuesto;

            var serializer = new JavaScriptSerializer();
            ViewBag.PresupuestoSeleccionado = serializer.Serialize(detalleP);

            return View(detalleP);
        }


        [HttpGet]
        public ActionResult EditarPresupuesto(int id_presupuesto)
        {
            as2oasis oasis = new as2oasis();
            AS2Context as2 = new AS2Context();
            var presupuesto =
                oasis
                .presupuesto_cabecera
                .AsEnumerable()
                .Where(x => x.id_presupuesto == id_presupuesto)
                .Select(x => new presupuesto_cabecera
                {
                    id_presupuesto = x.id_presupuesto,
                    descripcion = x.descripcion,
                    empresa = x.empresa,
                    sucursal = x.sucursal,
                    fecha_desde = x.fecha_desde,
                    fecha_hasta = x.fecha_hasta
                })
                .First();

            List<Presupuesto_Vendedor_Detalle> detallePresupuesto =
                oasis.Presupuesto_Vendedor_Detalle
                .AsEnumerable()
                .Where(x => x.id_presupuesto == id_presupuesto)
                .ToList();

            ViewBag.DetallePresupuesto = detallePresupuesto;

            var detalleP = new DetallePresupuesto();
            detalleP.id_presupuesto = presupuesto.id_presupuesto;
            detalleP.empresa = presupuesto.empresa;
            detalleP.sucursal = presupuesto.sucursal;
            detalleP.descripcion = presupuesto.descripcion;
            detalleP.fecha_desde = presupuesto.fecha_desde;
            detalleP.fecha_hasta = presupuesto.fecha_hasta;
            detalleP.ListaPresupuestoDetalle = detallePresupuesto;

            var serializer = new JavaScriptSerializer();
            ViewBag.PresupuestoSeleccionado = serializer.Serialize(detalleP);

            return View(detalleP);
        }

        [HttpPost]
        public ActionResult EditarPresupuesto(DetallePresupuesto presupuesto)
        {
            var id_presupuesto = presupuesto.id_presupuesto;
            if (presupuesto == null)
            {
                return HttpNotFound();
            }
            
            using (as2oasis oasis = new as2oasis())
            {
                var p_cabecera_act = oasis.presupuesto_cabecera.Where(s => s.id_presupuesto == id_presupuesto).First();
                p_cabecera_act.descripcion = presupuesto.descripcion;
                p_cabecera_act.fecha_desde = presupuesto.fecha_desde;
                p_cabecera_act.fecha_hasta = presupuesto.fecha_hasta;
                p_cabecera_act.activo = true;
                oasis.SaveChanges();
                var detalle_eliminar = oasis.presupuesto_detalle.Where(x => x.id_presupuesto_cabecera == p_cabecera_act.id_presupuesto);
                oasis.presupuesto_detalle.RemoveRange(detalle_eliminar);
                oasis.SaveChanges();
                foreach (var i in presupuesto.ListaPresupuestoDetalle)
                {
                    var p_detalle = new presupuesto_detalle();
                    p_detalle.presupuesto_cabecera = p_cabecera_act;
                    p_detalle.id_vendedor = i.id_vendedor;
                    p_detalle.valor_cobro = i.valor_cobro;
                    p_detalle.valor_venta = i.valor_venta;
                    oasis.presupuesto_detalle.Add(p_detalle);
                }
                oasis.SaveChanges();

                ModelState.Clear();


                ViewBag.SuccessMessage = "Se ha actualizado el presupuesto";
                return new JsonResult { Data = new { status = true } };


            }
        }


        public JsonResult ObtenerVendedores(string empresa, string sucursal, string textoBusqueda)
        {
            as2oasis oasis = new as2oasis();
            var vendedores = oasis.Vendedores
                .AsEnumerable()
                .Where(
                x =>
                //x.empresa == empresa && 
                //x.sucursal == sucursal &&
                (x.username.ToLower().Contains(textoBusqueda.ToLower()) == true
                || x.nombre.ToLower().Contains(textoBusqueda.ToLower()) == true))
                .GroupBy(x => new { x.id_vendedor, x.username })
                .Select(x => new
                {
                    id_vendedor = x.Key.id_vendedor,
                    username = x.Key.username,
                })
                .Take(5)
                ;

            //as2.empresa.Where(x=>x.) .invt_productos_gastos.Where(x => x.descripcion.Contains(textoBusqueda)).ToList();
            return Json(vendedores, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AnularPresupuesto(int id_presupuesto)
        {
            return null;
        }

        [HttpPost]
        public ActionResult Create(DetallePresupuesto presupuesto)
        {
            bool status = false;

            using (as2oasis oasis = new as2oasis())
            {
                bool duplicado = oasis.presupuesto_cabecera.Any(x => x.empresa == presupuesto.empresa
                    && x.sucursal == presupuesto.sucursal
                    && x.fecha_desde <= presupuesto.fecha_hasta
                    && x.fecha_hasta >= presupuesto.fecha_desde);

                if (!duplicado)
                {

                    var p_cabecera = new presupuesto_cabecera();
                    p_cabecera.empresa = presupuesto.empresa;
                    p_cabecera.sucursal = presupuesto.sucursal;
                    p_cabecera.descripcion = presupuesto.descripcion;
                    p_cabecera.fecha_desde = presupuesto.fecha_desde;
                    p_cabecera.fecha_hasta = presupuesto.fecha_hasta;
                    p_cabecera.activo = true;
                    oasis.presupuesto_cabecera.Add(p_cabecera);
                    oasis.SaveChanges();

                    int pk = p_cabecera.id_presupuesto;  // You can get primary key of your inserted row
                    foreach (var i in presupuesto.ListaPresupuestoDetalle)
                    {

                        var p_detalle = new presupuesto_detalle();
                        p_detalle.presupuesto_cabecera = p_cabecera;
                        p_detalle.id_vendedor = i.id_vendedor;
                        p_detalle.valor_cobro = i.valor_cobro;
                        p_detalle.valor_venta = i.valor_venta;
                        oasis.presupuesto_detalle.Add(p_detalle);
                    }
                    oasis.SaveChanges();
                    status = true;

                    ModelState.Clear();


                    ViewBag.SuccessMessage = "Se ha registrado el producto";
                    return new JsonResult { Data = new { status = status } };

                }
                else
                {
                    return null;
                }
            }
        }

        public ActionResult Index()
        {
            presupuesto_cabecera pre = new presupuesto_cabecera();
            as2oasis oasis = new as2oasis();
            var presupuesto =
                oasis
                .presupuesto_cabecera
                .AsEnumerable()
                .Where(x => x.activo == true)
                .Select(x => new presupuesto_cabecera
                {
                    id_presupuesto = x.id_presupuesto,
                    descripcion = x.descripcion,
                    empresa = x.empresa,
                    sucursal = x.sucursal,
                    fecha_desde = x.fecha_desde,
                    fecha_hasta = x.fecha_hasta
                });

            return View(presupuesto.ToList());

        }

       

    }
}

Oasis/Views/Presupuesto/DuplicarPresupuesto.cshtml
@model Oasis.ViewModel.DetallePresupuesto

@{
    ViewBag.Title = "Duplicar presupuesto";
}

@using (Html.BeginForm("Create","Presupuesto","POST"))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-12 col-sm-8">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Empresa</label>
                                <input id="empresa" name="empresa" value="@Model.empresa" hidden />
                                <h3>@Model.empresa</h3>
                            </div>
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Fecha desde</label>
                                <div  class="input-group date" id="fecha_desde_presupuesto" data-target-input="nearest">
                                    <input data-bind="text:fecha_desde" type="text" id="fecha_desde" name="fecha_desde" value="@Model.fecha_desde" class="form-control datetimepicker-input" data-target="#fecha_desde_presupuesto">
                                    <div class="input-group-append" data-target="#fecha_desde_presupuesto" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.form-group -->
                        </div>
                        <!-- /.col -->
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Sucursal</label>
                                <input id="sucursal" name="sucursal" value="@Model.sucursal" hidden />
                                <h3>@Model.sucursal</h3>
                            </div>
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Fecha hasta</label>
                                <div  class="input-group date" id="fecha_hasta_presupuesto" data-target-input="nearest">
                                    <input data-bind="text:fecha_hasta" type="text" id="fecha_hasta" name="fecha_hasta" value="@Model.fecha_hasta" class="form-control datetimepicker-input" data-target="#fecha_hasta_presupuesto">
                                    <div class="input-group-append" data-target="#fecha_hasta_presupuesto" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.form-group -->
                        </div>
                        <!-- /.col -->
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-8">
                            <div class="form-group">
                                <label>Descripcion</label>
                                <textarea data-bind="text:descripcion" class="form-control" 
                                          rows="3" id="descripcion" name="descripcion">@Model.descripcion</textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap" id="tablaPresupuesto">
                            <tr style="text-align:center;">
                                <th style="width:40px">
                                    CODIGO
                                </th>
                                <th style="width:250px">
                                    VISITADOR
                                </th>
                                <th>
                                    VALOR VENTAS
                                </th>
                                <th>
                                    VALOR COBROS
                                </th>
                            </tr>
                            <tbody data-bind="foreach: ListaPresupuestoDetalles">
                                @foreach (var item in ViewBag.DetallePresupuesto)
                                {
                                    <tr>
                                        <td>
                                            <div  name="id_vendedor">
                                                <input  id="id_vendedor" data-bind="text:id_vendedor" value="@item.id_vendedor" class="form-control" disabled/>
                                            </div>
                                        </td>
                                        <td>
                                            <select id="nombre_vendedor" name="nombre_vendedor" class="js-data-vendedor-ajax form-control" style="width:100%" name="state">
                                                <option value="@item.id_vendedor">@item.nombre_usuario</option>
                                            </select>
                                        </td>
                                        <td>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="fas fa-dollar-sign"></i>
                                                    </span>
                                                </div>
                                                <input data-bind="text:valor_venta" id="valor_venta" name="valor_venta" type="text" onchange="numeroDecimal" step='0.01' class="form-control" value="@item.valor_venta">
                                            </div>
                                        </td>
                                        <td>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="fas fa-dollar-sign"></i>
                                                    </span>
                                                </div>
                                                <input data-bind="text:valor_cobro" id="valor_cobro" name="valor_cobro" type="text" onchange="numeroDecimal" step='0.01' class="form-control" value="@item.valor_cobro">
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                    </div>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Regresar", "Index", new { @class = "btn" })
                    @*<button type="button" class="btn">Regresar</button>*@
                    <button  type="button" id="enviar"  class="btn btn-info float-right">Confirmar</button>
                </div>
            </div>
        </div>
    </div>
}
 

@section Scripts {
    <script src="~/Content/js/Presupuesto.js"></script>
    <script>
        ActivarVendedores();
        PresupuestoDetalle = []
        $('#enviar').click(function () {
            var tbl = $('#tablaPresupuesto tr:has(td)').map(function (i, v) {
                var $td = $('td', this);
                PresupuestoDetalle.push({
                    id_vendedor: $td.eq(0)[0].children[0].children[0].value,
                    valor_venta: parseFloat($td.eq(2)[0].children[0].children[1].value),
                    valor_cobro: parseFloat($td.eq(3)[0].children[0].children[1].value)
                })
            }).get();

            var datos = {
                empresa: $('#empresa').val().trim(),
                sucursal: $('#sucursal').val().trim(),
                descripcion: $('#descripcion').val().trim(),
                fecha_desde: $('#fecha_desde').val().trim(),
                fecha_hasta: $('#fecha_hasta').val().trim(),
                //valor_total: parseFloat($('#TotalPrincipalOC').val().trim()),
                //descuento: parseFloat($('#SubtotalPrincipalOC').val().trim()),
                //iva: parseFloat($('#IVAPrincipalOC').val().trim()),
                //iva: 0.00,
                ListaPresupuestoDetalle: PresupuestoDetalle,
            };

            $.ajax({
                url: 'Create',
                type: "POST",
                data: JSON.stringify(datos),
                dataType: "JSON",
                contentType: "application/JSON",
                success: function (d) {
                    if (d.status == true) {
                        Toast.fire({
                            icon: 'success',
                            title: 'Se ha creado el presupuesto.'
                        })
                        window.location.href = "index";
                    }
                },
                error: function (e) {
                    Toast.fire({
                        icon: 'error',
                        title: 'Hubo un error al intentar guardar.'
                    })
                }

            })
        });

        @*var presupuestoSeleccionado = '@Html.Raw(ViewBag.PresupuestoSeleccionado)';

        var parsedpresupuestoSeleccionado = JSON.parse(presupuestoSeleccionado);
        $(function () {
            //ko.applyBindings(ViewModel);
            var viewModel = new presupuestoModel();
            ko.applyBindings(viewModel);
        });

        function presupuestoModel() {
            var self = this;
            self.empresa = ko.observable(parsedpresupuestoSeleccionado.empresa);
            self.sucursal= ko.observable(parsedpresupuestoSeleccionado.id_vendedor);
            self.descripcion= ko.observable(parsedpresupuestoSeleccionado.descripcion);
            self.fecha_desde= ko.observable(parsedpresupuestoSeleccionado.fecha_desde);
            self.fecha_hasta = ko.observable(parsedpresupuestoSeleccionado.fecha_hasta);
            self.id_vendedor = ko.observable(parsedpresupuestoSeleccionado.id_vendedor);
            self.valor_venta= ko.observable(parsedpresupuestoSeleccionado.valor_venta);
            self.valor_cobro = ko.observable(parsedpresupuestoSeleccionado.id_vendedor);

            var ListaPresupuestoDetalle = {
                id_vendedor: self.id_vendedor,
                valor_venta: self.valor_venta,
                valor_cobro: self.valor_cobro
            };
            self.ListaPresupuestoDetalle = ko.observableArray();
            //self.ListaPresupuestoDetalles = ko.observableArray();

            self.datos = function () {
                var dato = ko.toJSON(this);
                console.log(dato);
            }
        }*@

        //function DetallePresupuesto(){
        //    var self = this;
        //    self.id_vendedor= ko.observable(parsedpresupuestoSeleccionado.id_vendedor),
        //    self.valor_venta= ko.observable(parsedpresupuestoSeleccionado.valor_venta),
        //    self.valor_cobro= ko.observable(parsedpresupuestoSeleccionado.valor_cobro)
        //}

        

        //var ViewModel =  {

        //    //var self = this;
        //    empresa: ko.observable(parsedpresupuestoSeleccionado.empresa),
        //    sucursal: ko.observable(parsedpresupuestoSeleccionado.id_vendedor),
        //    descripcion: ko.observable(parsedpresupuestoSeleccionado.descripcion),
        //    fecha_desde: ko.observable(parsedpresupuestoSeleccionado.fecha_desde),
        //    fecha_hasta: ko.observable(parsedpresupuestoSeleccionado.fecha_hasta),
        //    //DetallePresupuesto = {
        //    //    id_vendedor: ko.observable(parsedpresupuestoSeleccionado.id_vendedor),
        //    //    valor_venta: ko.observable(parsedpresupuestoSeleccionado.valor_venta),
        //    //    valor_cobro: ko.observable(parsedpresupuestoSeleccionado.id_vendedor)
        //    //},
        //    //ListaPresupuestoDetalle: ko.observableArray([DetallePresupuesto]),


        //    //self.agregarPresupuestoDetalle = function () {
        //    //    self.ListaPresupuestoDetalle.push(new DetallePresupuesto());
        //    //};

        //    verDatos: function () {
        //        console.log(ko.toJSON(this));
        //        //try {
        //        //    $.ajax({
        //        //        url: '/home/update',
        //        //        type: 'post',
        //        //        datatype: 'json',
        //        //        data: ko.tojson(this),
        //        //        contenttype: 'application/json',
        //        //        success: successcallback,
        //        //        error: errorcallback
        //        //    });
        //        //} catch (e) {
        //        //    window.location.href = '/home/read/';
        //        //}
        //    }

        //};
        //ko.applyBindings(new ViewModel());


        function Guardar() {
            var datos = ko.toJSON(ViewModel);
            console.log(datos);
        }



    </script>
}

Oasis/Views/Presupuesto/Index.cshtml
@model IEnumerable<Oasis.Models.presupuesto_cabecera>

@{
    ViewBag.Title = "Index";
    ViewBag.Modulo = "Presupuesto";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            @using (Html.BeginForm("Index", "Presupuesto", FormMethod.Get))
            {
                <div class="card-header">
                    <div class="card-tools">
                        <div class="input-group input-group-lg col-md-12">
                            @*@Html.ActionLink("Crear nuevo", "Create",                                      
                                        new { @class = "btn btn-lg btn-info" })*@
                            <a value="" class="btn btn-lg btn-info" href="Presupuesto/Create">
                                Crear nuevo
                            </a>
                        </div>
                    </div>
                </div>
                @*<p>
                        Búsqueda: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                        <input type="submit" value="" placeholder="Buscar..." />
                    </p>*@
            }
            <div class="card-body table-responsive">
                <table class="table table-hover text-nowrap" id="tablePresupuestoCabecera">
                    <thead>
                        <tr>

                            <th>
                                CODIGO
                            </th>
                            <th>
                                EMPRESA
                            </th>
                            <th>
                                SUCURSAL
                            </th>
                            <th>
                                FECHA DESDE
                            </th>
                            <th>
                                FECHA HASTA
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    @foreach (var item in Model)
                    {
                        <tr>

                            <td>
                                @Html.DisplayFor(modelItem => item.id_presupuesto)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.empresa)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.sucursal)
                            </td>
                            <td>
                                @item.fecha_desde.ToShortDateString()
                            </td>
                            <td>
                                @item.fecha_hasta.ToShortDateString()
                            </td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-outline-primary" data-toggle="dropdown" id="botonVerDetalle">
                                        <i class="fas fa-search"></i>
                                    </button>
                                    <button type="button" class="btn btn-outline-primary dropdown-toggle dropdown-hover dropdown-icon" data-toggle="dropdown" aria-expanded="false">
                                        <span class="sr-only"> Toggle Dropdown</span>
                                    </button>
                                    <div class="dropdown-menu" role="menu" style="">
                                        @Html.ActionLink("Editar", "EditarPresupuesto",
                                         new { id_presupuesto = item.id_presupuesto },
                                         new { @class = "dropdown-item" })
                                        @Html.ActionLink("Duplicar", "DuplicarPresupuesto",
                                         new { id_presupuesto = item.id_presupuesto },
                                         new { @class = "dropdown-item" })
                                        @Html.ActionLink("Anular", "AnularPresupuesto",
                                         new { controller = "AnularPresupuesto", id_presupuesto = item.id_presupuesto },
                                         new { @class = "dropdown-item" })
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }

                </table>
                <br />
                <div class="card-body">

                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts { 
    <script>
        $("#tablePresupuestoCabecera").DataTable({ 
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.10.24/i18n/Spanish.json'
            }
        });
    </script>

}