Oasis/Controllers/Proveedores/DetalleOrdenCompraController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Oasis.Models;
using Oasis.ViewModel;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Newtonsoft.Json;
using Oasis.Models.Login;

namespace Oasis.Controllers.Proveedores
{
    [CustomAuthorize(Roles = "Compras")]
    public class DetalleOrdenCompraController : Controller
    {
        public List<SelectListItem> ListaEmpresas()
        {
            List<SelectListItem> lst = new List<SelectListItem>();

            lst.Add(new SelectListItem() { Text = "LABOVIDA", Value = "LABOVIDA S.A." });
            lst.Add(new SelectListItem() { Text = "LEBENFARMA", Value = "LEBENFARMA S.A." });
            lst.Add(new SelectListItem() { Text = "FARMALIGHT", Value = "FARMALIGHT S.A." });
            lst.Add(new SelectListItem() { Text = "DANIVET", Value = "LABORATORIOS DANIVET S.A." });
            lst.Add(new SelectListItem() { Text = "DANIVET 2", Value = "LABORATORIOS DANIVET S.A. 2" });
            lst.Add(new SelectListItem() { Text = "ANYUPA", Value = "LABORATORIOS ANYUPA S.A." });
            lst.Add(new SelectListItem() { Text = "MEDITOTAL", Value = "MEDITOTAL S.A." });
            return lst;
        }

        [HttpPost]
        public JsonResult ListaOC()
        {
            as2oasis oa = new as2oasis();
            var listaOrdenComprar = oa.ordenes_compra
                .OrderByDescending(x => x.fecha)
                .AsEnumerable().Select(x => new
                {
                    Id_oc = x.id_orden_compra,
                    Empresa = x.empresa,
                    Secuencial = x.secuencial,
                    Fecha = x.fecha.ToShortDateString(),
                    Proveedor = x.cliente,
                    Total = x.valor_total,
                    Enlazado = x.orden_enlazada
                })
                .ToList();
            return new JsonResult { Data = listaOrdenComprar };
        }

        [HttpPost]
        public JsonResult ReporteOC()
        {
            as2oasis oa = new as2oasis();
            var detalleOrdenCompra = oa.DetalleOCEnlazada
                .OrderByDescending(x => x.fecha)
                .AsEnumerable()
                .Select(x => new
                {
                    empresa = x.empresa,
                    proveedor = x.proveedor,
                    ruc_proveedor = x.ruc_proveedor,
                    secuencial = x.secuencial,
                    fecha = x.fecha.ToShortDateString(),
                    departamento = x.departamento,
                    codigo_producto = x.codigo_producto,
                    descripcion_producto = x.descripcion_producto,
                    categoria_producto = x.categoria_producto,
                    um_producto = x.um_producto,
                    cantidad_producto = x.cantidad_producto,
                    valor_linea = x.valor_linea.ToString("N2"),
                    valor_total = x.valor_total.ToString("N2")
                })
                .ToList();
            return new JsonResult { Data = detalleOrdenCompra };
        }

        // GET: DetalleOrdenCompra
        public ActionResult Index()
        {
            ViewBag.Opciones = ListaEmpresas();
            return View();
        }

        public ActionResult Reporte()
        {
            return View();
        }

        //public ActionResult Detallar(string id_oc)
        //{
        //    ViewBag.Opciones = ListaEmpresas();
        //    return View();
        //}


        [HttpPost]
        public ActionResult Create(DetalleOrdenCompra ocModel)
        {
            bool status = false;
            using (as2oasis oasis = new as2oasis())
            {
                var oc_principal = new prov_oc_principal();
                oc_principal.fecha_documento = ocModel.fecha_documento;
                oc_principal.id_proveedor = ocModel.id_proveedor;
                oc_principal.valor_total = ocModel.valor_total;
                oc_principal.id_organizacion = ocModel.id_organizacion;
                oc_principal.id_departamento = ocModel.id_departamento;
                oc_principal.id_oc_principal = ocModel.id_oc_principal;
                oasis.prov_oc_principal.Add(oc_principal);
                oasis.SaveChanges();

                int pk = oc_principal.id_oc_principal;  // You can get primary key of your inserted row
                foreach (var i in ocModel.ListaDeDetalleOrdenCompra)
                {

                    var oc_detalle = new prov_oc_detalle();
                    //oc_principal.prov_oc_detalle.Add(i);
                    oc_detalle.prov_oc_principal = oc_principal;
                    oc_detalle.cantidad_producto = i.cantidad_producto;
                    //oc_detalle.descuento = i.descuento;
                    oc_detalle.id_producto = i.id_producto;
                    oc_detalle.valor_linea = i.valor_linea;
                    oasis.prov_oc_detalle.Add(oc_detalle);
                }
                oasis.SaveChanges();
                status = true;
            }
            ModelState.Clear();


            ViewBag.SuccessMessage = "Se ha registrado el producto";
            return new JsonResult { Data = new { status = status } };
        }

        // GET: Gastos/Details/5
        public void Imprimir(int id)
        {
            AS2Context as2_ = new AS2Context();
            as2oasis as2 = new as2oasis();
            var oc_detalle = new prov_oc_detalle();
            var detalle =
                as2.prov_oc_detalle
                .Where(x => x.id_oc_principal == id)
                .Select(x => new
                {
                    codigo = x.id_producto,
                    //descripcion = x.invt_productos_gastos.descripcion,
                    cantidad = x.cantidad_producto,
                    //um = x.invt_productos_gastos.um,
                    //valor_unitario = x.invt_productos_gastos.valor_unitario,
                    valor_linea = x.valor_linea
                });

            var principal =
                as2.prov_oc_principal
                .Where(x => x.id_oc_principal == id)
                .Select(x => new
                {
                    valor_total = x.valor_total,
                    anulada = x.anulada,
                    //empresa = x.empresa,
                    //departamento = x.id_dpto,
                    fecha_documento = x.fecha_documento,
                    ruc_proveedor = x.id_proveedor
                })
                ;

            var ruc_proveedor = principal.FirstOrDefault().ruc_proveedor;

            var proveedor =
                as2_.empresa
                    //.Where(x => x.identificacion == ruc_proveedor)
                    .Select(x => new
                    {
                        x.direccion_empresa.FirstOrDefault().ubicacion.direccion1,
                        x.direccion_empresa.FirstOrDefault().telefono1,
                        x.email1,
                        x.nombre_comercial
                    })
                    .FirstOrDefault();

            //var principal =
            //    oasis.prov_oc_principal
            //    //.Join(
            //    //    as2.empresa,
            //    //    principalOC => principalOC.id_proveedor,
            //    //    proveedor => proveedor.identificacion,
            //    //    (principalOC, proveedor) => new { PrincipalOC = principalOC, Proveedor = proveedor }
            //    //    )
            //    .Where(x => x.PrincipalOC.id_oc_principal == id)
            //    //.GroupBy(x=>new {x.PrincipalOC.id_oc_principal,x.PrincipalOC.anulada,
            //    //    x.PrincipalOC.departamentos.NOMBRE_DEPARTAMENTO,
            //    //    x.PrincipalOC.empresa,
            //    //    x.PrincipalOC.fecha_documento,
            //    //    x.PrincipalOC.id_proveedor,
            //    //    x.Proveedor.direccion_empresa,
            //    //    x.PrincipalOC.valor_total,
            //    //    x.Proveedor.email1,
            //    //})
            //    .Select(x=>new 
            //    {
            //        valor_total= x.Key.valor_total,
            //        anulada = x.Key.anulada,
            //        departamento = x.Key.NOMBRE_DEPARTAMENTO,
            //        empresa = x.Key.empresa,
            //        fecha_documento = x.Key.fecha_documento,
            //        ruc_proveedor = x.Key.id_proveedor,
            //        direccion_proveedor = x.Key.direccion_empresa,
            //        email = x.Key.email1
            //    })
            //    .First()
            //    ;

            //var detalle =
            //   oasis.prov_oc_detalle
            //  .Join(oasis.invt_productos_gastos,
            //    detalleOC=>detalleOC.id_producto,
            //    producto=>producto.id_producto,
            //    (detalleOC,producto)=>new {DetalleOC=detalleOC,Producto=producto })
            //  .AsEnumerable()
            //  .Where(x => x.DetalleOC.id_oc_principal == id)
            //  .Select(x => new
            //  {
            //      codigo = x.Producto.id_producto,
            //      producto = x.Producto.descripcion,
            //      cantidad = x.DetalleOC.cantidad_producto,
            //      um=x.Producto.um,
            //      valor_unitario = x.Producto.valor_unitario,
            //      valor_linea =x.DetalleOC.invt_productos_gastos.
            //      nombre_comercial = x.Key.nombre_comercial,
            //  })
            //  ;
            using (MemoryStream myMemoryStream = new MemoryStream())
            {
                Reporte R = new Reporte();
                R.Empresa = "LABOV";
                R.MemoryStream = myMemoryStream;
                var doc = R.CrearDoc();
                var pdf = R.CrearPDF();

                PdfPTable tabla_general = new PdfPTable(2)
                {
                    LockedWidth = true,
                    TotalWidth = 550f,
                    SpacingBefore = 4f
                };

Oasis/Views/DetalleOrdenCompra/Index.cshtml
@{
    ViewBag.Title = "Ordenes de compra";
}


<!--<div class="row">
    <div class="col-md-12">
        <div class="card card-primary">
            <div class="card-header">
                <h2 class="card-title">Ordenes de compra</h2>
                <div class="card-tools">
                    <button type="button" class="btn bg-primary btn-sm" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn bg-primary btn-sm" data-card-widget="remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>-->
            <!-- form start -->
            <!--<div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Empresa</label>
                            @Html.DropDownList("empresa_ind",
                                        new SelectList(ViewBag.Opciones, "Value", "Text"),
                                        htmlAttributes: new { @class = "form-control" })
                        </div>                       
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Región</label>
                            <select class="form-control" id="sucursal_ind">
                                <option value="COSTA">COSTA</option>
                                <option value="SIERRA">SIERRA</option>
                                <option value="AUSTRO">AUSTRO</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="button" id="DetalleIndividual" style="visibility: hidden" class="btn btn-info  float-left">Detalle individual</button>
                <button type="button" id="GenerarCartera" class="btn btn-primary  float-right">Generar</button>
            </div>
        </div>
    </div>
</div>-->

<div class="row">
    <div class="col-md-12">
        <div class="card card-primary">           
            <!-- form start -->
            <div class="card-body">
                <table id="tablaOC">
                    <thead>
                        <tr>
                            <th>Empresa</th>
                            <th>Secuencial</th>
                            <th>Fecha</th>
                            <th>Proveedor</th>
                            <th>Total</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tr>
                        <td></td>
                    </tr>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
</div>


@section Scripts {
    <script>
        $('#tablaOC').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ],
            "processing": true,
            //"serverSide": true,
            "ajax": {
                "url": "DetalleOrdenCompra/ListaOC",
                "type": "POST",
                "dataSrc": ""
            },
            "columns": [
                { "data": "Empresa" },
                { "data": "Secuencial" },
                { "data": "Fecha" },
                { "data": "Proveedor" },
                { "data": "Total" },
                { "data": "Enlazado" }
            ],
            columnDefs: [
                {
                    targets: 5,
                    render: function (data, type, row, meta) {
                        if (row.Enlazado == 0) {
                            return '<input type="button" class="btn btn-info form-control" onClick="Detallar('+row.Id_oc+')" data-id="' + row.Id_oc + '" value="Detallar"/>'
                        } else { 
                            return '<input type="button" class="btn btn-success form-control" onClick="VerDetalle(' + row.Id_oc +')" data-id="' + row.Id_oc + '" value="Enlazado" disabled/>'
                        }
                    }

                }
            ],
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.10.24/i18n/Spanish.json'
            }
        });

    </script>

    <script src="~/Content/js/OrdenCompra.js"></script>
    <script>

        function Detallar(id_oc) {
            var url = '@Url.Action("Create", "DetalleOrdenCompra")?id_oc=' + id_oc;
            window.location.href = url;
        }

        $('.cartera_visitador').change(
            function () {
                if (this.checked) {
                    $("#divVendedor").css('visibility', 'visible');
                }
            });

        $('.cartera_general').change(
            function () {
                if (this.checked) {
                    $("#divVendedor").css('visibility', 'hidden');
                    $("#DetalleIndividual").css('visibility', 'hidden');
                }
            });
        ActivarVendedores();

        function ActivarVendedores() {
            $('.js-data-vendedor-ajax').select2({
                //selectOnClose: true,
                minimumInputLength: 2,
                language: {
                    inputTooShort: function () {return "Ingresar dos o más caracteres";}
                },
                tags: [],
                ajax: {
                    url: '/Presupuesto/ObtenerVendedores',
                    processResults: function (data) {
                        return {
                            results: $.map(data, function (item) {
                                return {
                                    text: item.username,
                                    id: item.id_vendedor
                                }
                            })
                        };
                    },
                    dataType: 'json',
                    data: function (params) {
                        var query = {
                            textoBusqueda: params.term,
                            empresa: $('#empresa_ind').val(),
                            sucursal: $('#sucursal_ind').val()
                        }
                        return query;
                    }
                }
            }).on('change', function (e) {
                $("#DetalleIndividual").css('visibility', 'visible');
                //var id_vendedor = $(this).select2('data')[0].id_vendedor;
                //$(e.target).closest('#id_vendedor').val(id_vendedor);
            });
        }
    </script>
}

Oasis/Views/DetalleOrdenCompra/Reporte.cshtml
@{
    ViewBag.Title = "Reporte";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Reporte</h2>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <!-- form start -->
            <div class="card-body">
                <table id="tablaOC">
                    <thead>
                        <tr>
                            <th>Empresa</th>
                            <th>Proveedor</th>
                            <th>RUC</th>
                            <th>Secuencial</th>
                            <th>Fecha</th>
                            <th>Departamento</th>
                            <th>Código</th>
                            <th>Descripcion</th>
                            <th>Categoria</th>
                            <th>UM</th>
                            <th>Cantidad</th>
                            <th>Valor linea</th>
                            <th>Valor total</th>
                        </tr>
                    </thead>
                    <tr>
                        <td></td>
                    </tr>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
</div>


@section Scripts {
    <script>
        $('#tablaOC').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ],
            "processing": true,
            //"serverSide": true,
            "ajax": {
                "url": "ReporteOC",
                "type": "POST",
                "dataSrc": ""
            },
            "columns": [
                { "data": "empresa" },
                { "data": "proveedor" },
                { "data": "ruc_proveedor" },
                { "data": "secuencial" },
                { "data": "fecha" },
                { "data": "departamento" },
                { "data": "codigo_producto" },
                { "data": "descripcion_producto" },
                { "data": "categoria_producto" },
                { "data": "um_producto" },
                { "data": "cantidad_producto" },
                { "data": "valor_linea" },
                { "data": "valor_total" }
            ],
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.10.24/i18n/Spanish.json'
            }
        });

    </script>

}